# Generated by Django 5.1 on 2024-09-01 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0002_rename_adress_profile_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
